server:
  port: 8081

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://config-server:8888"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true   # habilita /actuator/health/liveness e /readiness
  tracing:
    enabled: true
  otlp:
    tracing:
      endpoint: http://otel-collector:4317
